name: 3. Create Certificates
run-name: Create Certificates (${{ github.ref_name }})

on: [workflow_call, workflow_dispatch]

env:
  TEAMID: ${{ secrets.TEAMID }}
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_TOKEN: ${{ secrets.GH_PAT }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
  FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
  FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit

  create_certs:
    name: Certificates
    needs: validate
    runs-on: macos-15
    outputs:
      new_certificate_needed: ${{ steps.set_output.outputs.new_certificate_needed }}

    steps:
      # Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # Install dependencies
      - name: Install Project Dependencies
        run: bundle install

      # Patch fastlane match table output
      - name: Patch Match Tables
        run: |
          TABLE_PRINTER_PATH=$(bundle exec ruby -e 'spec = Gem::Specification.find_by_name("fastlane"); puts File.join(spec.gem_dir, "match/lib/match/table_printer.rb")')
          if [ -f "$TABLE_PRINTER_PATH" ]; then
            sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
          else
            echo "table_printer.rb not found at: $TABLE_PRINTER_PATH"
            exit 1
          fi

      # Sync clock
      - name: Sync clock
        run: sudo sntp -sS time.windows.com

      # Create / update certs
      - name: Check and create or update Distribution certificate and profiles if needed
        run: |
          echo "Running Fastlane certs lane..."
          bundle exec fastlane certs || true

      - name: Check Distribution certificate and launch Nuke certificates if needed
        run: bundle exec fastlane check_and_renew_certificates
        id: check_certs

      # Set outputs
      - name: Set output and annotations based on Fastlane result
        id: set_output
        env:
          ENABLE_NUKE_CERTS: ${{ vars.ENABLE_NUKE_CERTS }}
          FORCE_NUKE_CERTS: ${{ vars.FORCE_NUKE_CERTS }}
        run: |
          CERT_STATUS_FILE="${{ github.workspace }}/fastlane/new_certificate_needed.txt"

          if [ -f "$CERT_STATUS_FILE" ]; then
            CERT_STATUS=$(cat "$CERT_STATUS_FILE" | tr -d '\n' | tr -d '\r')
            echo "new_certificate_needed: $CERT_STATUS"
            echo "new_certificate_needed=$CERT_STATUS" >> $GITHUB_OUTPUT
          else
            echo "Certificate status file not found. Defaulting to false."
            CERT_STATUS="false"
            echo "new_certificate_needed=false" >> $GITHUB_OUTPUT
          fi

          if [ "$CERT_STATUS" != "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
            echo "::notice::üîî Automated renewal of certificates is disabled because ENABLE_NUKE_CERTS is not set to 'true'."
          fi

          if [ "$CERT_STATUS" = "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
            echo "::error::‚ùå No valid distribution certificate found. ENABLE_NUKE_CERTS is not 'true'."
            exit 1
          fi

          if [ "$FORCE_NUKE_CERTS" = "true" ]; then
            echo "::warning::‚ÄºÔ∏è Nuking of certificates was forced because FORCE_NUKE_CERTS is set to 'true'."
          fi

  nuke_certs:
    name: Nuke certificates
    needs: [validate, create_certs]
    runs-on: macos-15
    if: ${{ (needs.create_certs.outputs.new_certificate_needed == 'true' && vars.ENABLE_NUKE_CERTS == 'true') || vars.FORCE_NUKE_CERTS == 'true' }}
    steps:
      - name: Output from step id 'check_certs'
        run: echo "new_certificate_needed=${{ needs.create_certs.outputs.new_certificate_needed }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane nuke_certs
        run: |
          set -e
          bundle exec fastlane nuke_certs

      - name: Recreate Distribution certificate after nuking
        run: |
          set -e
          bundle exec fastlane certs

      - name: Add success annotations for nuke and certificate recreation
        if: ${{ success() }}
        run: |
          echo "::warning::‚ö†Ô∏è All Distribution certificates and TestFlight profiles have been revoked and recreated."
          echo "::warning::‚ùóÔ∏è Run '3. Create Certificates' for other apps that rely on shared certificates."
          echo "::warning::‚úÖ Existing TestFlight builds will keep working."
